### ISSUE TITLE
[Bug] Selecting Steam during set-up causes instant crash

### ISSUE THREAD

**Issue by Razozo** [zencq/NomNom#106]
### Description
Attempting to select steam as an option to locate saves instantly, and causes the crash collector to appear.

### Reproduce
1. Open app.
2. Select Steam.
3. App crashes.

### Additional Context
Add any other context about the problem here or at least complete the following information.
 - Version: 4.00.0.32-beta.2
 - Platform: Steam
 - OS: Windows 11 22H2

**Comment by cengelha** [comment]
@Razozo Can you provide a crash report?
