### ISSUE TITLE
[Bug] Crash when trying to transfer a save from Microsoft to Steam

### ISSUE THREAD

**Issue by TwistedGate** [zencq/NomNom#107]
### Description
So i've tried to transfer my Microsoft save over to Steam since it's running out this month. (And i got NMS for steam now cus sale)
But when the moment i click the two arrows, the program just nukes itself.

### Reproduce
1. Open the `Save Transfer` option.
2. Set source as `Microsoft`
3. Select a save file and leave everything as is.
4. Set destination as `Steam`
5. Select an empty slot.
6. Hit the arrows.
7. Hopefully witness a crash.

### Expected Behavior
Well, what it says on the tin realy.

### Files
[Gist of Log and Generated Crash File](https://gist.github.com/TwistedGate/fcdb1e996f7fdff1c1db4c79329501e3)
As for the save file itself, if it's absolutely nessesary i'll trying get it.

### Additional Context
 - Version: 4.00.0.32-beta.2
 - Platform: Microsoft → Steam

---
If there's anything else i can do, please let me know. I'd happily be a guinea pig :)
(Im also in the Discord server, just incase, for convenience)

**Comment by momos11** [comment]
Did you find a way or is it still broken?

**Comment by GuestJ1** [comment]
I was having this issue as well, but I found that the save transfer worked if instead of selecting an empty slot in step 5, you overwrite the save in the destination.
