### ISSUE TITLE
The only files I can access after unzipping are the MD files. 

### ISSUE THREAD

**Issue by Blastogasm** [zencq/NomNom#11]
The only files I have in the folder are as follows:
.github
images
.gitignore
_config.yml
AutoUpdater
CHANGLOG
FEATURES
LICENSE
README
ROADMAP

I would just like to know if there is something I did wrong here, none of these files except for the MD files allow for me to access them or even open them. If I could get some assistance with this it would be greatly appreciated. Thanks.

**Comment by ProfYakkington** [comment]
Looks like you downloaded the "code" for this project and not the compiled release version.
You can find them here https://github.com/cengelha/NomNom/releases

**Comment by Blastogasm** [comment]
Oh my thank you, I'm kind of new to messing with github so that was greatly appreciated!
