### ISSUE TITLE
[Bug] Application crashes without internet access

### ISSUE THREAD

**Issue by LeeC2202Git** [zencq/NomNom#113]
### Description
Application crashes when it has no internet access.

### Reproduce
Run the application with no internet access

### Expected Behaviour
As there is no listed requirement for internet access, then I simply expected the application to run without error.

If there is a requirement for internet access, then several things need to be added to comply with privacy concerns.
1) A statement explicitly stating that internet access is required.
2) The reason that internet access is required.
3) Details about what information is collected and transmitted both in and out of the machine with regards to this internet connection.
4) An option to disable the internet requirement.

### Additional Context
Add any other context about the problem here or at least complete the following information.
 - Version: 4.0 Beta 2
 - Platform: Steam
[CrashReport.zip](https://github.com/zencq/NomNom/files/10336670/CrashReport.zip)

**Comment by cengelha** [comment]
I never experienced an issue w/o internet access but looks like the updater makes some trouble (despite it doesn't work atm). It's currently the only feature that requires internet access but shouldn't cause a crash... (there is a feature flag system as well tho, but that's not a real feature)

An overview about used online services and what data are send/received is already in the works and will be part of the wiki that will be published here on GitHub in the wiki section soon. 

Giving you more control over the behavior of features requiring internet access is already on my list.

**Comment by Pd69bq** [comment]
experienced the same issue here, and found some "suspicious" entries in the crash report, I'm also really curious why a simple app has to visit github.com (phone home!?) every time it starts

> Exception
> 
> Type
> 
> System.Net.Http.HttpRequestException
> 
> Message
> 
> A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (github.com:443)

**Comment by cengelha** [comment]
Hey, as I mentioned, it's the built-in update feature. It checks whether a new version is available at every start. This not different than in the goatfungus editor nor new or "secretly" added. It's like this since the 3rd alpha almost 3 years ago and mentioned in the [changelog](https://github.com/zencq/NomNom/blob/master/CHANGELOG.md#2203-alpha3-2020-04-26).

And as I also mentioned in the post before, all online services will soon be explained in detail in the upcoming wiki and giving you more control in NomNom itself is already on the todo list as well.

**Comment by LeeC2202Git** [comment]
> I never experienced an issue w/o internet access but looks like the updater makes some trouble (despite it doesn't work atm). It's currently the only feature that requires internet access but shouldn't cause a crash... (there is a feature flag system as well tho, but that's not a real feature)
> 
> An overview about used online services and what data are send/received is already in the works and will be part of the wiki that will be published here on GitHub in the wiki section soon.
> 
> Giving you more control over the behavior of features requiring internet access is already on my list.

No problem. Out of habit, all downloaded exe files are blocked from the internet on my PC, it avoids me having to packet sniff to see what is happening in the communication chain. I also downloaded NMSCoordinates at the same time as this and that shows the same lack of internet connection in the onscreen log window but carries on running without error.

Most people don't run things without an internet connection so crashes like this are easily missed. Even though this might only be an update check, I prefer to have full control over that checking. As a developer with decades-worth of projects on my PCs, I don't leave anything to chance with unknown exe files and online communication.
