### ISSUE TITLE
[Doesn't open | Crash] 

### ISSUE THREAD

**Issue by TheCodexMaster** [zencq/NomNom#115]
### Description
Doesn't open and crashes immediately without log when opening nomnom.exe

### Reproduce
opening the file itself crashes immediately

### Expected Behavior
Expected it to work

### Files
A screen recorded video
https://user-images.githubusercontent.com/116146426/213381360-091e36ba-e5e5-4e36-a41c-22e52998cd07.mp4

### Additional Context
Add any other context about the problem here or at least complete the following information.
 - Version: 4.0
 - Platform: Laptop [e.g. Steam, PlayStation]

**Comment by TheCodexMaster** [comment]
I've installed .NET 6.0.13 so there's no problem in that

**Comment by nguyer** [comment]
I just started encountering this behavior after running my Steam copy of the game for the first time. Previously I was able to launch it with no copy of the game installed, or the Windows Store version of the game. NomNom was able to detect the Windows Store version after running it for the first time. But now it won't load after I started the Steam version.

**Comment by nguyer** [comment]
Hmm. Actually I just deleted the whole NomNom directory and re-extracted the zip file and it's working fine now.

**Comment by Abaldwin0916** [comment]
Did you figure it out?

**Comment by TheCodexMaster** [comment]
It's been months since i opened this issue, no longer an issue, it's solved
