### ISSUE TITLE
[Bug] Crash when trying to open Microsoft save

### ISSUE THREAD

**Issue by frostworldgames** [zencq/NomNom#116]
### Description
I get a "System.OutOfMemoryException" crash when trying to open the NMS Microsoft PC version save.

### Reproduce
1. Open Program, Autodetects Platform
2. Click on 'Platform Save: Microsoft'

### Expected Behavior
To open the save file to edit.

### Files
[NomNom 4.00.0.32-beta.2 Crash Report.pdf](https://github.com/zencq/NomNom/files/10819437/NomNom.4.00.0.32-beta.2.Crash.Report.pdf)

### Additional Context
 - Game Version: 4.1 Fractal
 - Platform: Microsoft PC
 - NomNom Save Editor Version: 4.00.0.32-beta.2

**Comment by YanezDiego** [comment]
I am also experiencing this bug. Even after deleting and unzipping again (which might have not been the best decision) I am still receiving this issue.

**Comment by twieland** [comment]
Same here. I'm trying to convert an Xbox (GamePass) file to Steam, but it's already crashing when opening the file.

**Comment by CameronJThomas** [comment]
+1 for this issue. I don't even get a chance to click on the save before it crashes.

```
Exception of type 'System.OutOfMemoryException' was thrown.

at System.Text.Encoding.GetString(Byte[] bytes)
at System.Text.UTF8Encoding.UTF8EncodingSealed.GetString(Byte[] bytes)
at libNOM.io.Extensions.IEnumerableExtensions.GetString(IEnumerable`1 self)
at libNOM.io.Extensions.IEnumerableExtensions.GetJson(IEnumerable`1 self)
at libNOM.io.Platform.DeserializeContainer(Container container, Byte[] binary)
at libNOM.io.Platform.BuildContainer(Container container)
at libNOM.io.Platform.BuildContainer(Int32 metaIndex, Object extra)
at libNOM.io.PlatformMicrosoft.<>c__DisplayClass69_0.<BuildContainerCollection>b__0()
at System.Threading.Tasks.Task`1.InnerInvoke()
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

**Comment by Brutestrength115** [comment]
I also have this issue

**Comment by CameronJThomas** [comment]
For anyone desperate, the original editor by goatfungus is up-to-date and working with the latest version. https://github.com/goatfungus/NMSSaveEditor

I just used it to transfer my Xbox save to Steam, albeit a little more manually than this tool (create new save in Steam version -> open Xbox save -> export JSON -> open Steam save -> import JSON -> save changes -> open Steam version again -> bob's your uncle).

Hopefully this one gets some TLC soon.

**Comment by Brutestrength115** [comment]
Thank you @CameronJThomas

**Comment by desolation0** [comment]
This was the behavior I experienced as well.

To add to this, if starting from fresh unpack and clicking the Microsoft install first my install of NomNom was then unable to initialize. It would close out after launch before any UI elements were loaded. Needed to delete portable.config to reset the settings. Trying again would once again crash out and require deleting the config file before rebooting.

Windows 10 if that information helps.

Uploading the report as html didn't function, so converted it to .txt extension, sorry for any inconvenience.
[report.20230302181944 - Copy.txt](https://github.com/zencq/NomNom/files/10874790/report.20230302181944.-.Copy.txt)
