### ISSUE TITLE
[Bug] Can't start NomNom

### ISSUE THREAD

**Issue by Aaroneisele55** [zencq/NomNom#127]
### Reproduce

1. start NomNom on a fresh install from GitHub
2. try to select your platform
3. the app crashes and can't be reopened until the PC is restarted

### Expected Behavior
It should just work

### Files
[To make it easier to reproduce your problem it can be helpful to attach your save folder.
Please also attach the crash report (if any) and your log file.
If applicable, add screenshots to help explain your problem.]
I have attached two crash reports of this problem in thezip file:
[crashreports.zip](https://github.com/zencq/NomNom/files/11411877/crashreports.zip)

### Additional Context
Add any other context about the problem here or at least complete the following information.
 - Version: latest
 - Platform: Steam

**Comment by cengelha** [comment]
@Aaroneisele55 Can you attach your save folder? Seems to be something I can't fix without reproducing.
