### ISSUE TITLE
[Bug] crash when changing edited save file

### ISSUE THREAD

**Issue by SaltyRhino95857-2** [zencq/NomNom#129]
### Description
error `Value cannot be null. (Parameter 'key')` when changing edited save file

### Reproduce
1. Go to `Manager`
2. Click on another save file
3. crash
4. ...

### Expected Behavior
not crash and change the save file

### Files
Change file to `.html` before viewing because GitHub doesn't support sending `.html`s
[report.20230621104920.txt](https://github.com/zencq/NomNom/files/11818505/report.20230621104920.txt)

### Additional Context
Add any other context about the problem here or at least complete the following information.
 - Version: [`4.00.0.32-beta.2`]
 - Platform: [`Microsoft Store`]
[report.20230621104920.txt](https://github.com/zencq/NomNom/files/11818505/report.20230621104920.txt)

**Comment by zararashigal** [comment]
Still not fixed btw.

**Comment by zararashigal** [comment]
<img width="799" height="472" alt="Image" src="https://github.com/user-attachments/assets/7399d5c8-3316-45ac-ba27-baffc750fea4" />
