### ISSUE TITLE
[Bug] Freighter Class Not Changing 

### ISSUE THREAD

**Issue by Dominic-Dom** [zencq/NomNom#139]
### Description
Freighter class shows it changes in editor but not in game. 

### Reproduce
Click Changer Freighter class
Change from c to s class 
Save 
Transfer save to switch 
Open game 
Freighter class stays as it was 

### Expected Behavior
Freighter class to change 

### Files
N/A but I can make them if you need them to be 

### Additional Context
 - Version: 4.4.5
 - Platform: [e.g. switch]

**Comment by cengelha** [comment]
I couldn't reproduce it with 5.00.1 (anymore), so I consider this done.
