### ISSUE TITLE
Having trouble acquiring twitch and expedition rewards. They are now unlocked but I can't aqcuire them and it won't let me lock them back. If I do attempt to lock them it crashes the mod. On Microsoft App for XBOX

### ISSUE THREAD

**Issue by d3ad81rd** [zencq/NomNom#141]

**Comment by monskey8** [comment]
Bump. Same issue for me, trying to acquire expedition rewards on Steam account after unlocking through save editor.

**Comment by cengelha** [comment]
Sounds like a misunderstanding how this works. 
When you unlock them in account, the rewards are unlocked everywhere. Except those rewards you have to collect explicitly (Ships, Weapons, Pets), everything is directly unlocked/useable.
When you claim something in-game, in that save you don't see it anymore but in every other save it is still visible and says "Previously Claimed”. You can hide that by also claiming it in a specific save.
If you want to claim Ships, Weapons, Pets again or if you marked them as claimed in a save by accident you have to lock them again in that specific save.
If you get a crash doing so, please upload the report here to make fixing it easier :)
