### ISSUE TITLE
Fresh install on new widows 11 fails to start

### ISSUE THREAD

**Issue by jDmacD** [zencq/NomNom#142]
### Description
New install on windows 11. Followed the instructions and installed `"C:\Users\macdo\Downloads\dotnet-sdk-6.0.417-win-x64.exe"`.  
On launching NomNom it creates some folders. 

```sh
PS C:\Program Files\NomNom> ls

    Directory: C:\Program Files\NomNom

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        24/11/2023     00:37                collection
d-----        24/11/2023     00:40                log
d-----        24/11/2023     00:37                modding
d-----        24/11/2023     00:17                runtimes
-a----        24/11/2023     00:17           3725 NomNom.dll.config
-a----        24/11/2023     00:17      255495266 NomNom.exe
-a----        24/11/2023     00:40           1440 portable.config
-a----        24/11/2023     00:17         161240 WebView2Loader.dll
```

The splash screen shows, then nothing.  
No error message.  
Nothing in the logs directory.  
Save game is where it's expected to be `C:\Users\TylerDurden\AppData\Roaming\HelloGames\NMS\st_76561198030997251`
Ran it as Administrator, no joy.  
I enabled the debug flags in `C:\Program Files\NomNom\portable.config`
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <userSettings>
    <Roaming>
      <NomNom.Properties.Settings>
        <Culture>en</Culture>
        <Version>4.40.0.34</Version>
        <RunningDialog>True</RunningDialog>
        <ModeAdvanced>False</ModeAdvanced>
        <LandingPage>ManagerView</LandingPage>
        <ModeAutosave>False</ModeAutosave>
        <LastWriteTime>True</LastWriteTime>
        <DonationEmail></DonationEmail>
        <ModeRestriction>Default</ModeRestriction>
        <Debug>True</Debug>
        <ModeDebug>True</ModeDebug>
        <OpenDiscordApp>True</OpenDiscordApp>
        <Advanced>False</Advanced>
      </NomNom.Properties.Settings>
    </Roaming>
    <PC_WARPCORE>
      <NomNom.Properties.Settings>
        <PreferredPlatform></PreferredPlatform>
        <LoadingStrategy>Partial</LoadingStrategy>
        <PathCollection>C:\Program Files\NomNom\collection</PathCollection>
        <Autosave>False</Autosave>
        <MaxBackupCount>3</MaxBackupCount>
        <PathSave></PathSave>
        <SessionCount>2</SessionCount>
        <LastPlatform></LastPlatform>
        <WindowPosition>300, 150</WindowPosition>
        <PathDefaults></PathDefaults>
        <WelcomeFlag>True</WelcomeFlag>
        <WindowSize>1360, 768</WindowSize>
        <SavePath></SavePath>
      </NomNom.Properties.Settings>
    </PC_WARPCORE>
  </userSettings>
</configuration>
```
And a log file was created containing:
```txt
2023-11-24 00:40:25.906 +00:00 [INF] Starting session 2...
```

### Reproduce
1. Download and install dotnet
2. Reboot
3. Download and unzip NomNom to `C:\Program Files\NomNom\`
4. Double click on `NomNom.exe`

### Expected Behavior
The program to start
### Files
To make it easier to reproduce your problem it can be helpful to attach your save folder.
Please also attach the crash report (if any) and your log file.

### Additional Context
Add any other context about the problem here or at least complete the following information.
 - Version: 4.40.0.34
 - Platform: Steam
#### Windows Info
- Edition: Windows 11 Home
- Version: 23H2
- Installed on: ‎05/‎11/‎2023
- OS build: 22631.2715
- Experience: Windows Feature Experience Pack 1000.22677.1000.0
#### Steam Info
- Steam Version:  1700160213
- Steam Client Build Date:  Thu, Nov 16 6:25 PM UTC -08:00
- Steam Web Build Date:  Thu, Nov 16 6:06 PM UTC -08:00
- Steam API Version:  SteamClient021

![image](https://github.com/zencq/NomNom/assets/6770688/6d71e0dc-36ab-4bac-b084-d627c4874b1c)

**Comment by jDmacD** [comment]
Similar to https://github.com/zencq/NomNom/issues/115

**Comment by cengelha** [comment]
Does it still happen with the new version (.35)?

**Comment by Blend3rman** [comment]
> Does it still happen with the new version (.35)?

@cengelha 
I was running into the same issue with the newest version. Splash screen showed up and disappears. I managed to fix it by editing `portable.config` and updating the `PathCollection` variable to where I unpacked NomNom. It was pointing to the System32 folder by default. I also extracted NomNom into my D: drive instead of C: drive, which could have contributed to the issue.

**Comment by cengelha** [comment]
Thanks for the info! Now I have a starting point where to look :)

**Comment by cengelha** [comment]
See #155 or as mentioned #115 for a solution.

**Comment by cengelha** [comment]
See #155 or as mentioed #115
