### ISSUE TITLE
[Feature Request] Frighter Expeditions

### ISSUE THREAD

**Issue by NimaDolatabadi** [zencq/NomNom#144]
I would be great if expeditions difficulties would be change higher than 3 star. I have search a lot it does not incease more than 3.
Regards
Nima
![image](https://github.com/zencq/NomNom/assets/32169409/3cffde96-bea0-4c78-9250-828dfeb18906)

**Comment by cengelha** [comment]
This is nothing that can be changed in the editor. The game generates it dynamically. I think this levels with you/your freighter/fleet.
