### ISSUE TITLE
[Bug] NomNom crashes after new update

### ISSUE THREAD

**Issue by cfragkos** [zencq/NomNom#147]
### Description
NomNom crashes after new update

### Reproduce
Open nomnom click edit

### Files
[report.20240215092820.zip](https://github.com/zencq/NomNom/files/14294175/report.20240215092820.zip)

### Additional Context
Add any other context about the problem here or at least complete the following information.
 - Version: [4.5 omega]
 - Platform: [ Steam]

**Comment by EradiusLore2** [comment]
Having the same issue. might be unrelated but i was able to access the save right up to the point where i changed to the pirate freighter. changing to another freighter didnt fix the issue. 
[report.zip](https://github.com/zencq/NomNom/files/14296882/report.zip)

**Comment by Pd69bq** [comment]
same System.OutOfMemoryException

**Comment by Urakabaramiel** [comment]
Hello, same problem, appears after upgrade to version 4.50 (OMEGA) - System.OutOfMemoryException.

**Comment by Vorprail** [comment]
I have the same problem

**Comment by Urakabaramiel** [comment]
Good morning, is there any information somewhere as to whether the work has started, possibly when there will be a new working version. I can't find information anywhere. I am, of course, patiently waiting. However, it would be nice to know anything.
