### ISSUE TITLE
Access to my Protected documents wanting to Delete MS Backup?

### ISSUE THREAD

**Issue by DS-Karma** [zencq/NomNom#15]
Any idea why this wants to access and Delete MSBackup? My Virus Protector Flagged this this morning when running NomNom after a PC Update.

**Comment by cengelha** [comment]
It doesn't do that. NomNom only works with files in the save and output paths you define and even then, it only touches the necessary save files and in the output path the subfolder it creates.

The only other thing that happens implicitly is .NET stuff that is handled by the .NET platform itself and I don't have control over that nor should that affect anything besides the executing program.

Maybe a false-positive?
Or name confilcts in the output path? NomNom creates/uses _backup_, _crash_, _json_, and _log_ in it.

**Comment by MisterTarget** [comment]
Its false flag because you wanted to open it in Desktop i assume? I had the same error but it somehow just conflicts with the Desktop

**Comment by cengelha** [comment]
I couldn't reproduce it, even extracted to the Desktop.
As there is no further information provided and @MisterTarget confirmed that it's a false-positive, this will be closed now.
