### ISSUE TITLE
Ability to add Guide entries

### ISSUE THREAD

**Issue by Watchman3001** [zencq/NomNom#151]
### Description
An ability to add/toggle guide entries. Extremely simple and straight. Seems like due to my save being old, some guide entries are missing despite me being in endgame. So... Yeah, would love that feature

By Guide I mean that section of journal
![image](https://github.com/zencq/NomNom/assets/87601407/5d4a7a95-0dd6-47f3-93a5-5c8e851561dd)

**Comment by cengelha** [comment]
You can already do that when editing account data:
![image](https://github.com/zencq/NomNom/assets/37042388/e389c844-92e7-4455-988f-d0fc1d2a9bf2)
