### ISSUE TITLE
Adding Guide entry is bugged, and won't actually save it? 

### ISSUE THREAD

**Issue by Watchman3001** [zencq/NomNom#152]
### Description
TIcking both "seen" and "unlocked" on guide entries I didn't had before, gave out a weird result. When entering my journal, I can see those entries in right top corner, and I can click on them to visit them, read everything, e.t.c. But after I close that window with the text, Guide entry doesn't actually save. It is not in the list where it should be. And btw, I think those entries keep appearing in that right top corner

### Reproduce
1. Tick "seen" and "unlocked" in save editor, click "save account"
2. Enter the game, go to your journal
3. Check Guides section
4. Entries you added are not actually in the list

### Expected Behavior
Those entries to be there. Simple

### Additional Context
Last version of the game, latest version downloaded from Github and updated

**Comment by cengelha** [comment]
For me it works. Did you edit it while the game was running? Editing account data works best/only if you start the game afterwards.

**Comment by Watchman3001** [comment]
> For me it works. Did you edit it while the game was running? Editing account data works best/only if you start the game afterwards.

Nope, game was closed. Don't tell me I messed up my save and it is irreversible now😅

**Comment by cengelha** [comment]
This has been reported fixed via Discord.
