### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Dxthly** [zencq/NomNom#153]
just got back into no mans sky and completed the new expedition and got all rewards I tried to unlock all previous expedition rewards with the save editor and it just says "previously unlocked" I claimed the Normandy and living frigate everything else was already unlocked apart from quicksilver stuff couldn't claim the expedition 1 ship or the rest of the stuff like eggs 
 - Platform:  Windows/Xbox Series X

**Comment by cengelha** [comment]
To get rid of the "previously unlocked" you have to unlock them in account AND save.
Account tells the game it has been unlocked/claimed somewhere und for most of the rewards this will then work in all saves (hence the "previously unlocked"). 
Just note that ships,weapons,pets must be claimed in-game to actually get them for a save (as their configuration is stored in the save)
