### ISSUE TITLE
[Bug] "Edit" button does nothing when clicked 

### ISSUE THREAD

**Issue by DizzyDJW** [zencq/NomNom#154]
### Description
Edit button does nothing when clicked

### Reproduce
1. Open NomNom
2. Highlight Save File
3. Click "Edit" button
4. Watch as nothing happens...

### Expected Behavior
Something... Literally anything... Even a crash would be fine....

### Additional Context
 - Version: 4.40.0.34-beta.4
 - Platform: Steam

**Comment by Navkie** [comment]
Have the same issues. Same version same platform. Windows 10. I can EDIT the account. The moment I click on the grid of the save files. The whole application freezes.

**Comment by elegault** [comment]
+1! It works...sometimes
