### ISSUE TITLE
[Bug] New Install - "Welcome" blank, can't change options or configure

### ISSUE THREAD

**Issue by aelfwyne** [zencq/NomNom#155]
### Description
On a new install of NomNom (unable to test upgrading existing install), there is no text on the welcome screen. A blank box which is tall and narrow, with no dialog buttons appears with the title Welcome. It is 100% blank inside the box.  Closing the box allows one to access the menus in the app, but settings changes don't save.  I have tried setting the save folder, and it appears to set, but when I close settings and re-open it, the line is blank again. All items on the main screen are grayed out (presumably because I haven't configured the save folder). The three dot (...) button to set the folder does not respond. If the folder is typed manually it accepts input but doesn't save.

### Reproduce
1. Install files from latest beta6 for omega in an empty directory.
2. Run NomNom.Exe
3. See a blank welcome screen with no setup wizard.
4. Attempt setup on the menu, it won't accept folder input for save folder.

### Expected Behavior
Expected is that it can be configured and at least SEE the save files (which are Omega). 

### Files
It never gets to the point of even configuring the save folder, so save files are not relevant. No logfile is generated, although the Log folder is created.  
![image](https://github.com/zencq/NomNom/assets/1447876/1ddbd654-84ad-491c-b82a-a9f53715e62e)

### Additional Context
Add any other context about the problem here or at least complete the following information.
 - Version: [4.50.1.36-beta.6](https://github.com/zencq/NomNom/releases/tag/4.50.1.36-beta.6)
 - Platform: Windows 11

**Comment by aelfwyne** [comment]
Workaround:

Through a lot of trial and error I was able to manually configure the portable.config file. This issue appears to be present in all downloaded versions of 4.x. 

Once I manually configured the portable.config file with all the relevant paths and platform, the program now recognizes my saves and appears to work.

**Comment by Blend3rman** [comment]
> Once I manually configured the portable.config file with all the relevant paths and platform, the program now recognizes my saves and appears to work.

Could you provide a paste of your manual configuration? I am running into a similar issue (NomNom splash screen shows up but then the app crashes). I'd like to see if this might fix it.

**Comment by earwigcahootz** [comment]
Same issue here. My PathCollection variable was already set to the correct location for \NomNom\collection.

**Comment by cengelha** [comment]
Deleting the entry in the config (or the entire file) should do the trick, otherwise skipping "Welcome" and selecting a folder manually (File -> Open) should work too

**Comment by cwpnw** [comment]
The Collection Manager on the base tab does not load any of the saved collections.  I have attempted the recommendations above but they have not caused any collections to load. The manager will not add or remove bases. 

I'm using the portable version
Version: 5.60.O+29f5d2133adc3c800002f6c48e7ebfadaa490cbf
Build Date: 4/2/2025 1:23:43 PM
