### ISSUE TITLE
[Bug] "RocketLockerInventory" is labeled "FireteamSessionCount" in the JSON

### ISSUE THREAD

**Issue by Lenni009** [zencq/NomNom#165]
### Description
In the save JSON, the "RocketLockerInventory" section is labeled "FireteamSessionCount".

This happens due to a duplicate key in the save mapping.

### Reproduce
1. Open your save JSON
2. Search for "RocketLockerInventory"
3. -> Notice it finds nothing
4. Search for "FireteamSessionCount"
5. -> See it finds a section that looks like an inventory and therefore belongs to the "RocketLockerInventory" key.

### Expected Behavior
The key should be "RocketLockerInventory"

### Additional Context
Add any other context about the problem here or at least complete the following information.
 - Version: 4.52
 - Platform: Steam

**Comment by cengelha** [comment]
You found a hash collision in the MBINC mapping.json! If you look at it, you'll find the 2 having both "V86".
As "FireteamSessionCount" is later in the file, "RocketLockerInventory" is overwritten and therefore not used.

Is "FireteamSessionCount" more than once in you file? If not, it makes indeed sense to favor "RocketLockerInventory" over "FireteamSessionCount".

**Comment by Lenni009** [comment]
`FireteamSessionCount` only exists once. `RocketLockerInventory` doesn't exist at all. If I look at the raw, unmapped JSON, `V86` only appears once. So `FireteamSessionCount` might be deprecated or something?

**Comment by cengelha** [comment]
I checked the MBINC repo and it seems that `FireteamSessionCount` is only used in account data (`GcUserSettingsData`).
Would probably be best if the account mappings would be separately in the file and not mixed with the other ones.
