### ISSUE TITLE
[Bug] Can't edit Settlement Perks and also they always get reset or blanked when saving the game on The Save editor

### ISSUE THREAD

**Issue by Chariot7000** [zencq/NomNom#167]
### Description
Whenever I save the game on the save editor my Settlement Perks get blanked as if they didn't existed, and if I try to Edit them when I save the game on the Editor it gets reverted back to before.

### Reproduce
1. Go to Settlements
2. Edit the perks on the save editor
3. Save it, and the or the perks gonna get erased and deleted or they will change to what it was before when you log in the game.

### Expected Behavior
Editing the perks should just edit them and not erased them when we save the game, if you enter the game after editing it or they will be erased or have non change at all or revert back to a previous state.

### Additional Context

I am playing on Xbox Omega update (the last version before Orbital since Xbox didn't received Orbital yet).

This has also happened a few times last month but I always managed to fix the Perks of the settlements with the Goatfungs save editor but their save editor now it's not working unfortunately.

**Comment by kpstool** [comment]
Same problem, and these perks cannot be changed.
They are all set to blank and have a value -1.
