### ISSUE TITLE
[Bugs] List of a few bugs that always happens when saving in your editor

### ISSUE THREAD

**Issue by Chariot7000** [zencq/NomNom#169]
### Description
Always when I edit something and save using your save editor my freighter goes to class C, a few of my frigates do to C and all my perks of my Settlement gets blanket without an option to reactivate, your save editor is really good but this bugs are very annoying I always have to restar my Settlement if I want to use your save editor.

### Reproduce
Edit anything with the save editor and check your in-game freighter, frigates and settlement, sometimes for some reason the bugs doesn't happen but it happens 80% of the time.

### Expected Behavior
It shouldn't alter things I didn't changed.

### Additional Context
I play on Gamepass/Xbox/Microsoft Store.

**Comment by cengelha** [comment]
I couldn't reproduce it with 5.00.1 (anymore), so I consider this done.
