### ISSUE TITLE
cant run the mod

### ISSUE THREAD

**Issue by thePyromaniac09564** [zencq/NomNom#174]
Im having trouble getting to mod to connect to the game itself, im playing on steam and still relatively new to windows computers so it might just be a mistake on my end but i cant figure out how to run the mod
![image](https://github.com/zencq/NomNom/assets/171855948/3596d41a-3f28-4e93-a0a8-6aee88342ccd)
heres what the app looks like if that can solve any questions

**Comment by cengelha** [comment]
Please try deleting the `portable.config` file and/or selecting the save path manually (File -> Open).
The default path for Steam is `%AppData%\HelloGames\NMS`

**Comment by thePyromaniac09564** [comment]
> ###
> [Jun 11, 2024](#issuecomment-2161542164)

thx for the help, i kinda forgot about the post here so i just deleted it and waited for an update. i redownloaded it just now and it works just fine
