### ISSUE TITLE
[Bug] App crash after new update

### ISSUE THREAD

**Issue by drdoom766** [zencq/NomNom#175]
### Description
Program crashed when trying to add item into multi-tool with error: Requested value 'SearchSolid' was not found.

### Reproduce
1. Go to 'Multi-Tool'
2. Click on 'Add/Replace Item'
3. Crash

### Files
Crash log included.

[NomNom 4.70.0.39-beta.9+7a504f678934196ffc787d643ab3a0bf568d1b7a Crash Report.pdf](https://github.com/user-attachments/files/15778038/NomNom.4.70.0.39-beta.9%2B7a504f678934196ffc787d643ab3a0bf568d1b7a.Crash.Report.pdf)

**Comment by drdoom766** [comment]
Also happens in other screen while trying to add items

**Comment by cengelha** [comment]
It will be fixed in the next release. A preview can be found here: https://github.com/zencq/NomNom/releases/download/4.70.0.39-beta.9/NomNom-4-70-1-preview.1.zip

**Comment by Dolphin263** [comment]
> It will be fixed in the next release. A preview can be found here: https://github.com/zencq/NomNom/releases/download/4.70.0.39-beta.9/NomNom-4-70-1-preview.1.zip

Is this the experimental release save refactor, or a different issue?  If the same, then it's sweet you already have a fix!

If it is a different issue, note that the current experimental release changes the save game format and you might want to look at it.  https://steamcommunity.com/app/275850/discussions/0/4333106094377537940/,
