### ISSUE TITLE
[Bug] cant open save files 

### ISSUE THREAD

**Issue by Cheeseman2121** [zencq/NomNom#176]
### Description
the program can see my save files but does not want to open them when i click edit

### Reproduce
1. open program
2. Click on save file
3. click edit
4. program freezes
5. nothing happens

on newest version

**Comment by BlueKittyMeow** [comment]
I'm experiencing the exact same error. I can edit my account data by clicking on the edit button for that section, however I am unable to edit any save file.

**Comment by KevFerguson** [comment]
Same as @BlueKittyMeow here. Account editing is fine, but cannot load saves.

**Comment by FleetOfWarships** [comment]
Same problem, though it doesn't freeze on my end, it just doesn't do anything. Account editing works fine.

**Comment by bloodheart56** [comment]
Same issue

**Comment by cengelha** [comment]
Can any of you send me their saves for reproducing?

**Comment by FleetOfWarships** [comment]
I would but mine is working now weirdly, can still send it though if needed.

**Comment by bloodheart56** [comment]
> Can any of you send me their saves for reproducing?

It seems to only happen when the new ship (Iron Vulture) is your active ship, as long as it's not your active ship it works. but also does not recognize it in the ships tab
