### ISSUE TITLE
[Bug] Old Settlement ownership after save transfer

### ISSUE THREAD

**Issue by InspirationAndMotivation** [zencq/NomNom#177]
### Description
Bug with Planetary Settlement transfer. If you transfering account from Xbox to Steam Planetary Settlement isn't your anymore. You still can resolve NPC's problems, but not building (adding resources) nor renaming as well. Also you can't check information about Planetary Settlement, because you have message that this option available only for Overseer which is another player. When I played some time, found new Planetary Settlement and transfer my save back - when I tried to open New Planetary Settlement's info - game freezed and showed me stats with all max baff and 199 citizens everywhere.

![image](https://github.com/zencq/NomNom/assets/44005458/46b2e3fc-5a4e-4dff-9cc8-c3497f76c972) 

### Reproduce
1. Open application, go to "Edit" -> "Save transfer"
2. On the left side pick your save from Xbox with existing Planetary Settlement and on the right side pick Steam account and save that you want to rewrite. Click on "Start transfer" in the middle.
3. Launch your game from Steam and pick your transferred save -> you can check Overseer's Office and find out that it isn't your anymore. 
4. [Bonus] If you will find new Planetary Settlement and transfer your save back - it will break your second Planetary Settlement. You will be able to do anything you want beside openning your Settlement info

### Expected Behavior
Open and close your Planetary Settlement's information, be able meet citizens and build new buildings.

### Additional Context
 - Version: Nomnom 4.70.1.40-beta.10 
 - Platforms: Steam and Xbox

**Comment by cengelha** [comment]
I think the problem here is, that settlements are automatically uploaded and as mentioned in the transfer window, uploaded things cannot be transferred (the ownership reset to be more precises).
Therefore, I can't really to anything about it (other than removing the checkbox and adding a note about it)
