### ISSUE TITLE
[Bug] Editing account data doesn't save

### ISSUE THREAD

**Issue by JacobZufall** [zencq/NomNom#180]
### Description
When you load your save and click "Edit" under "Account", no changes made there will save. I've tried making changes there, clicking "Save" and "Save Account", yet the changes have no effect on the game. Closing and reopening the application also shows that the changes don't save.

### Reproduce
1. Open NomNom
2. Load save
3. Click "Edit" under the "Account" section
4. Make changes to something in the account data. For example, unlock an expedition reward under "Quicksilver Synthesis Companion"
5. Save changes
6. Reload save file and witness the lack of changes

### Expected Behavior
It should save as it says.

### Additional Context
Add any other context about the problem here or at least complete the following information.
 - Version: 4.70.2.41-beta
 - Platform: Steam

**Comment by Facu221196** [comment]
still no solution for this?

**Comment by JacobZufall** [comment]
> still no solution for this?

I mean, I just opened the issue today. I'm sure the owner has some higher priorities with the release of v5.0 of the game.
