### ISSUE TITLE
Save transfer crashing [Bug]

### ISSUE THREAD

**Issue by hiran5** [zencq/NomNom#182]
### Description
When transfering Saves from Xbox Game Pass to PC with Save transfer feature, NomNom closes unexpectedly without warning or recognition of crash.

### Reproduce
1. Go to 'Edit
2. Click on 'save transfer'
3. Scroll down to 'Microsoft saves and select specific save file wanting to transfer
4.  nomnom starts not responding and crashes

### Expected Behavior
in previous editions when using save transfer the save transfer work lag for a brief moment while readying the file before allowing me to transfer to my steam saves.

### Files
no crash log available, no window reporting unexpected crash, 

### Additional Context
Add any other context about the problem here or at least complete the following information.
 - Version: [e.g. 4.70.2.41]
 - Platform: [transfering from Xbox Game pass version 4.72 to Steam 5.0 part 1 world]

**Comment by realadamsmith** [comment]
any updates on this, also, wheres the exe file in the github repo?

**Comment by cengelha** [comment]
@realadamsmith In the [releases](https://github.com/zencq/NomNom/releases). The repo itself is not the right place for the exe ;)
