### ISSUE TITLE
[Bug] Editor Crashes when trying to load any saves.

### ISSUE THREAD

**Issue by shy-fox** [zencq/NomNom#183]
### Description
The editor crashes when trying to open any saves, giving me an exception of `System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.`

### Reproduce
1. Open the application
2. Attempt to load a save

### Expected Behavior
I used this editor previously, it loaded my saves just fine, that's what I expected to happen.

### Files
[Crash Report File](https://github.com/user-attachments/files/16321175/report.20240720125617.zip)

### Additional Context
Add any other context about the problem here or at least complete the following information.
 - Version: 4.70.2.41-beta.11
 - NMS Version: Worlds I
 - Platform: Steam

**Comment by amcculley** [comment]
NMS Worlds 1 is version 5 of NMS.  You are using 4.70 of the app.  Version 5 isn't out yet.

**Comment by Arnost-Mandoade** [comment]
Why would you expect the save editor which is updated to NMS 4.70 to work on version 5.0 of NMS which is a huge overhaul of the game? Seriously, read patch notes.

**Comment by cengelha** [comment]
@shy-fox Can you send me your save folder? From the report it looks like that at least one save has corrupted data (messed up compression)

**Comment by cengelha** [comment]
Assuming this is solved due to missing response.
