### ISSUE TITLE
not allowed to create a json file it just shows up and isnt selectable, im just assuming its becuz im on the newest version of nms but im not sure. ive spent the last 3 hours trying anything to get it to work.[Bug] 

### ISSUE THREAD

**Issue by MuahahahaBooty** [zencq/NomNom#185]
Its just wont let me create a json file ive tried everything.

**Comment by MuahahahaBooty** [comment]
i just open nomnom and try to crete a json file with no luck. i have all the requirements

**Comment by archraziel** [comment]
To enable the edit json button, you have to click on File -> Settings and check the Advanced Mode box.
Is this what you want?

**Comment by cengelha** [comment]
@MuahahahaBooty Please try the 5.00 update and let me know if the issue is still present. (Or did the answer from archraziel already solve it for you?)

**Comment by cengelha** [comment]
Assuming this is solved due to missing response.
