### ISSUE TITLE
[Bug 4.70.3.42-beta.12 - NMS WORLDS] Unable to read, transfer or deserialize Game Pass Save Game 

### ISSUE THREAD

**Issue by laryakan** [zencq/NomNom#186]
### Description
Unable to read, transfer or deserialize Game Pass Save Game. I bought the game on GoG and I wanted to transfer my XBOX GAME PASS save to GoG. I red about your great tool, and after adding and exception on my antivirus thinking that your tool is a trojan, I manager to see my save (GoG and Xbox Game Pass). Everything seems fine with my GoG Save, my Game Pass save seems unreadable, NomNom is telling my I'm on Custom Game Mode and is not able to tell me that I'm on WORLDS. Save game are tagged "incompatible" (unable to deserialise to JSON) and I'm not able to transfer my GAME PASS save.

### Reproduce
1. Go to 'NomNom'
2. Click on 'Xbox Game Pass Save'
3. Try to deserialize it, edit, transfer or anything else

### Expected Behavior
Being able to transfer my files from Game Pass Save to GOG Save

### Files
![Capture d'écran 2024-07-25 144938](https://github.com/user-attachments/assets/0a0a21aa-1ff6-423c-9354-f1349e69ecd8)
![Capture d'écran 2024-07-25 145727](https://github.com/user-attachments/assets/ec2eafbc-87f5-4bef-8df2-87b46450ee6e)

[report.20240725130027.zip](https://github.com/user-attachments/files/16378046/report.20240725130027.zip)

### Additional Context
Add any other context about the problem here or at least complete the following information.
 - Version: 4.70.3.42-beta.12
 - Platform: XBOX Windows App, GOG Galaxy, NMS WORLDS

**Comment by CaptaiWacko** [comment]
The tool hasn't been updated for NMS Worlds yet, hopefully is should be up soon.
