### ISSUE TITLE
[Bug] Can't transfer GoG save to Xbox Gamepass/Windows

### ISSUE THREAD

**Issue by TankZealot** [zencq/NomNom#189]
### Description
When transfering save from GoG to Game pass through the "Save transfer" function, the game pass version sees the game time and which world you are in inside the main menu. But when you start the transferred save the game just starts from the beginning, like when you start a new game. You get the "Begin installation". 

The GoG save is updated to same version as Xbox Game pass.

It works when transferring Xbox Game pass save to GoG but not the other way around.

 - Version: 5.00.0.44-beta.13
 - Platform: GoG -> Xbox Gamepass/Windows

**Comment by silentstranger5** [comment]
Same issue when attempting to transfer save from Steam to Xbox.

**Comment by oOJonnyOo** [comment]
Same issue

**Comment by Max5872** [comment]
Hello,

Just tried with the last release 5.00.2.46-beta.15 but I get the same initial issue when transfer from Steam to Xbox.

Any Idea ?

Thanks

**Comment by TankZealot** [comment]
> Hello,
> 
> Just tried with the last release 5.00.2.46-beta.15 but I get the same initial issue when transfer from Steam to Xbox.
> 
> Any Idea ?
> 
> Thanks

Same issue here
