### ISSUE TITLE
[Bug] Export does not work from Edit menu

### ISSUE THREAD

**Issue by Lenni009** [zencq/NomNom#192]
### Description
When trying to export a save to JSON from the "Edit" header, it does not work.

### Reproduce
1. Select a save
2. Hover over "Edit" in the top row, next to "File"
3. Click "Export to JSON"
4. Nothing happens

### Expected Behavior
The JSON file should be generated in the `json` folder

### Additional Context
Add any other context about the problem here or at least complete the following information.
 - Version: 5.00.0.44-beta.13
 - Platform: Steam, Gamepass

It does work when clicking "Edit JSON" and then clicking "Export" there.

**Comment by cengelha** [comment]
It actually does what it says but put it in a different location. I changed to be both in .`/json` (file name still differs tho).

**Comment by Lenni009** [comment]
Out of curiosity, where was it saved before? I don't think I found anything in any of the NomNom subfolders

**Comment by Lenni009** [comment]
I think I found it, directly next to the actual save files
