### ISSUE TITLE
[Bug] can't acquire certain items from the older expeditions.

### ISSUE THREAD

**Issue by Troll6868** [zencq/NomNom#195]
I acquired the items with the account modification
- went into account 
- collect expedition reward
- selected unlock all
Then I went in game and tried to collect the rewards but when I press on a reward the cursor loads fully but doesn't actually collect it. I'm having the same issue with a twitch rewards I got from actually watching streams (not with this tool)

**Comment by Troll6868** [comment]
Fixed it
It was because I already "claimed" the items using the save function so I just had to unclaim them (lock) in the save tab then claim them in the account tab

**Comment by cengelha** [comment]
Glad you found the solution. Would have suggested that too ;)
