### ISSUE TITLE
[Bug] When clicking the save edit button nothing happens 

### ISSUE THREAD

**Issue by Dominic-Dom** [zencq/NomNom#197]
### Description
When on editor I click edit save button and nothing happens.

### Reproduce
1. Open editor 
2. Click Save edit button 

### Expected Behavior
Open save details and let me edit 

### Additional Context
 - Version: [5.00.1.45-beta.14]
 - Platform: [Switch, Game on 5.0.2]

**Comment by Tameth** [comment]
same problem, Account Edit works, but the Save Edit button does not open anything to edit now.

**Comment by ThiccJuicyPiglet** [comment]
Im having the same problem, I updated my Nom Nom and now the edit save button does nothing on any of my saves.
