### ISSUE TITLE
File integrity check Failure updating nomnom to 5.00.3

### ISSUE THREAD

**Issue by Talardor** [zencq/NomNom#204]
### Reproduce
1. Launch Beta 15 of nomnom.
2. click the Update Now button
3. On completion of the download, I get the error "File integrity failed and reported some errors"

### Expected Behavior
NomNom to be updated from 5.00.2.46 to 5.00.3 and be ready to use

### Files
![image](https://github.com/user-attachments/assets/e7535311-e127-427d-b16c-c15f4b6b6722)

### Additional Context

Add any other context about the problem here or at least complete the following information.
 - Version: 5.00.3
 - Platform:  Steam

**Comment by runlykhel** [comment]
yep same thing

**Comment by cengelha** [comment]
has been fixed now
