### ISSUE TITLE
[Bug] Save file shows "GAMEMODE_Invalid" after editing JSON

### ISSUE THREAD

**Issue by Lenni009** [zencq/NomNom#207]
### Description
After editing the JSON in NomNom, the file can no longer be saved or edited.

### Reproduce
1. Load a save in NomNom
2. Edit JSON
3. Do a small edit, like changing the `RealityIndex`
4. Save the JSON edit and close the JSON editor
5. See the "Edit" and "Save" buttons being greyed out, and the file showing "GAMEMODE_Invalid"

### Expected Behavior
The JSON edit should result in a valid save file that can be saved or edited further.

### Files
[save12.zip](https://github.com/user-attachments/files/16697731/save12.zip)

### Additional Context
Add any other context about the problem here or at least complete the following information.
 - NomNom Version: 5.00.3
 - Platform: Steam

**Comment by spideruk07** [comment]
same issue here same version same platform

**Comment by cengelha** [comment]
Workaround that worked for me is to not select a node on the tree on the left. But I'm looking for a proper fix.
