### ISSUE TITLE
[Bug]  - Edit Save not working

### ISSUE THREAD

**Issue by MikeDiko** [zencq/NomNom#211]
### Description
Edit save not working

### Reproduce
1. select platform and path as normal, until the list of saves
2. Click on the latest save as to have it selected
3. On the left menu, under "Save" click "Edit"
 - after a few seconds of froze, nothing happens

by comparison:
5. Go to settings check "Advanced"
6. Under "Save" click "Edit JSON..." button, works as normal

### Additional Context
This is with the latest game expansion Aquarius (5.10) on Steam and latest NomNom version, 5.10

**Comment by Graysonn** [comment]
same is happening to me.

**Comment by StainlessSteele** [comment]
Same issue here.
