### ISSUE TITLE
[Bug]  Integer and other crashes

### ISSUE THREAD

**Issue by ZataraTMM** [zencq/NomNom#216]
### Reproduce
1. starship
2. details on a tech item
3. edit seed
4. get integer crash
5. Couldn't find any enum member that matches the integer -1

### Expected Behavior
the seed for a blackmarket item to be changed and work after pressing save.

### Files
To make it easier to reproduce your problem it can be helpful to attach your save folder.
Please also attach the crash report (if any) and your log file.

### Additional Context
Add any other context about the problem here or at least complete the following information.
-I'm trying to change the seed of a ship tech, i put it in, exit, and whenever i save whole program crashes. 
Couldn't find any enum member that matches the integer -1
I'm constantly getting similar crashes whenever i save, also always saying 1 unsaved change do u wanna exit, even after saving multiple times it's always 1 unsaved. Is there something i'm missing? i was using portable but switched to normal, still getting a fuckton of crashes at saving or editing something. 

Another crash. I click on my save, at the start the blue button to rollback to it, not doing anything else, getting Nullable object must have a value. after pressing save.

**Comment by cengelha** [comment]
Can you attach the crash report the next time you experience this? Would help me a lot to find the correct spot to fix this. 

The unsaved change message is a known thing, and I have it on my list. If you saved you can usually ignore it for now.
