### ISSUE TITLE
[Bug] Crash after edit Profile or Save

### ISSUE THREAD

**Issue by get4** [zencq/NomNom#219]
Hello,
i have since the NMS October Update 24 the red circle load error.
This Problems comes with the new version and i can change only 1 thing(credits/expidition gift or ship) in Profile or Save and save and get this error.

Windows10
NMS Windows V5.21 - Oct 26
NomNom V5.20 - Oct 27

Thanks

**Comment by cengelha** [comment]
Can you explain it a bit more, and maybe add a crash report or the log (from the log folder) if any? I'm not sure what you mean with "red circle load error"

**Comment by get4** [comment]
Its not a nomnom crash. I change something with nomnom and save the files. After save i start NMS and i see only the never ending loading screen
![images](https://github.com/user-attachments/assets/7bc8ebb0-4580-443a-8b35-f460785d58aa)

Before Updating No Mans Sky and NomNom, i change/save anything without this problem. the problem comes with the new version for expoidition 16.

**Comment by get4** [comment]
Ok its solved. Deinstall the version. Install the .net and web kit again and used the portable version... after x Saves its ok.

**Comment by get4** [comment]
Ok its solved. Deinstall the version. Install the .net and web kit again and used the portable version... after x Saves its ok.
