### ISSUE TITLE
Ps4 save not detected

### ISSUE THREAD

**Issue by Avrution** [zencq/NomNom#22]
I have tried pulling saves from two different PS4's, but Nomnom won't detect them, so there is nothing I can open.

One save it from the OG game back during release, so I tried opening a newer version save from a different PS4, but it still isn't recognized.

Files are untouched and pulled fresh using save mounter.

Ideas where to start?

**Comment by Aeramis** [comment]
Did you decrypt the save via advanced mode on save wizard and export the memory.dat file?

Also, right now it seems there is an issue with saving the modified file in NomNom. Hopefully it gets fixed soon.

**Comment by Avrution** [comment]
I didn't use save wizard, this was done with save mounter. For some reason 
the newest save ended up being empty, so I will have to try that one again. 
I know the save from around the release date has data, it just may be too 
old to read.

**Comment by cengelha** [comment]
@Avrution NomNom only supports Beyond (2.14) and up but it might recognize that it's a PS4 save at least. But if it's from the first (or near that) NMS release four years ago and not recognized at all, HG might have changed the internal file structure or something so NomNom tries but fails and as it haven't found any saves/files it could handle, it just ignores it and shows nothing in the manager

@Aeramis You can expect a new release later today

**Comment by Avrution** [comment]
Thanks, I figured that might be it.  I will find a way to update the save on the PS4 and extract again.

**Comment by Aeramis** [comment]
> 
> 
> @Avrution NomNom only supports Beyond (2.14) and up but it might recognize that it's a PS4 save at least. But if it's from the first (or near that) NMS release four years ago and not recognized at all, HG might have changed the internal file structure or something so NomNom tries but fails and as it haven't found any saves/files it could handle, it just ignores it and shows nothing in the manager
> 
> @Aeramis You can expect a new release later today

Cool. Hope all goes well. I really like your version of the editors.
