### ISSUE TITLE
i actually have a question but it could also be a feature request if it isn't already a feature.

### ISSUE THREAD

**Issue by rexrobotwars** [zencq/NomNom#33]
i wanted to know if there is a way to transfer items from the catalog into the your inventory because i have been messing around with it to no avail it would help if there was a guide on what exactly you could do with the save editor or if there is one i would very much like to know were that might be, your help would be appreciated.

**Comment by cengelha** [comment]
You might have figured it out on your own but a few words nonetheless.

There is no real guide but this [FEATURES](https://github.com/cengelha/NomNom/blob/master/FEATURES.md) file where I listed everything you can do with NomNom.

Not entirely sure what you meant but you can add items to your inventories. But not transfer them between the inventories (yet).
