### ISSUE TITLE
[Bug] JSON editor doesn't work

### ISSUE THREAD

**Issue by TowerTop498** [zencq/NomNom#36]
### Description
Despite having Advanced Mode turned on, I'm still unable to use the JSON Editor feature.

### Steps to Reproduce

1. Turn on Advanced Mode under File > Mode
2. Use JSON Editor under Edit

### Expected Behavior
Opening the JSON file and allowing the user to edit

### Actual Behavior
JSON Editor is grayed out and unable to be selected

- Version with issue: Latest
- Platform you use: Xbox Game Pass for PC

### Screenshots
![image](https://user-images.githubusercontent.com/68376827/108585210-1388f580-72fc-11eb-96c1-4f04e491cb2b.png)
![image](https://user-images.githubusercontent.com/68376827/108585225-2a2f4c80-72fc-11eb-9312-2daea0ede9f7.png)

**Comment by cengelha** [comment]
It's not a bug but a non-functional prototype. This will be cleanup up (menu entry removed) before beta and re-added when it's properly done.
