### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by MonkeyAcid** [zencq/NomNom#40]
### Steps to Reproduce

1.
2.
3.

### Basic Information

- Version with issue:
- Platform you use:

**Comment by cengelha** [comment]
@mikey1975 Please add any information or I will close this.

**Comment by mikey1975** [comment]
Good day,

Pls close this, as I wanted to submit a crash, but completely unaware how to do it.

Sorry for any inconvenience caused.

Regards

Sent from ProtonMail mobile

-------- Original Message --------
