### ISSUE TITLE
[Feature Request] The ability to see/edit/export the overall save settings for PS4 saves

### ISSUE THREAD

**Issue by cyberpunk2350** [zencq/NomNom#46]
## Summary
On Steam overall game settings can be changed by editing the file %ProgramFiles(x86)%\Steam\steamapps\common\No Man's Sky\Binaries\SETTINGS\GCUSERSETTINGSDATA.MXML
This includes things like Twitch Rewards, Expedition Regards, Titles, Catalog info.  Looking to be able to edit the same info on a PS4 save

## Details
The same info found in the GCUSERSETTINGSDATA.MXML for Steam saves is located at the start of the memory.dat file part of the PS4 save.  Looking for a method that allows users to see, edit, and export this data.  This info is stored in JSON format in the memory.dat vs MXML for steam.

**Comment by cengelha** [comment]
Thanks! I'm already aware of it and already implemented it partially for all 3 platforms. Won't be (visible) in the next version but perhaps in the one after that.

**Comment by cengelha** [comment]
The next version will include this but not for PlayStation unfortunately, as SaveWizard doesn't let you convert the `SAVEDATA00` which contains that data now.

**Comment by cengelha** [comment]
This works for homebrew theoretically for SW too, if they convert that file...
