### ISSUE TITLE
How goes the Work for a MS-Store Compatibility?

### ISSUE THREAD

**Issue by DS-Karma** [zencq/NomNom#6]
Nice to see something being done recently on a NMS Save Editor.

I have done a load of digging and tried some things myself, the issue I am having is I am not quite sure what file holds the savegames. Anyway... how goes your work on getting it compatible with the MS-Store?

**Comment by cengelha** [comment]
It is postponed to a later release. At the moment I'm focused on the finalization of the next one, which lays the foundation for it, among other things. The next one will be for the Desolation update, which will add the new items and such.
After that I will come back to the MS Store compatibility.
