### ISSUE TITLE
[Bug] Can't find the executable

### ISSUE THREAD

**Issue by ElBretzelito** [zencq/NomNom#89]
Not many things to describe here
I downloaded the zip, extracted it
looked everywhere in the files, not exe 
I tried to do it multiple times just incase, updated my java, rebooted my computer, no change 

Am I missing something ?

**Comment by cengelha** [comment]
Hi, the executable is (and never will be) part of the repo itself. To get the executable go to the main page and scroll down to [Download](https://github.com/cengelha/NomNom#download) or directly click on [Releases](https://github.com/cengelha/NomNom/releases) on the right. Open the assets of the latest release and download "NomNom.zip".
