### ISSUE TITLE
Saves on Microsoft Store/Xbox shown as incompatible

### ISSUE THREAD

**Issue by technofox01** [zencq/NomNom#90]
Hi!

I really love your program; however, I am unable to convert my Steam saves to Microsoft Store/Xbox. When I attempt to load the save, it says it is incompatible. Can you please fix this?

**Comment by cengelha** [comment]
Hi, 
it's a known issue but unfortunatly all efforts to find the reason or solve this weren't sucessfull...

But! Your save isn't really incompatible even if the game says so. There is a workaround solve this: Reboot your PC and it will be  compatible again. This isn't ideal but the only way for now.
