### ISSUE TITLE
[Bug] Seem there is no .exe file in the downloadable Zip (PC)

### ISSUE THREAD

**Issue by MattisMatt** [zencq/NomNom#97]
### Reproduce
2. Click on '...'
3. Scroll down to '...'
4. ...

### Files
To make it easier to reproduce your problem it can be helpful to attach your save folder.
Please also attach the crash report (if any) and your log file.

### Additional Context
Add any other context about the problem here or at least complete the following information.
 - Version: [e.g. 3.7.0.23]
 - Platform: [e.g. Steam, PlayStation]

**Comment by MattisMatt** [comment]
Hello
It seems there is no .exe file in the downloadable Zip (PC)

**Comment by cengelha** [comment]
You have to download a release, not the source code: https://github.com/cengelha/NomNom/releases

**Comment by MattisMatt** [comment]
Hello
thanks a lot for your reply, sorry I ve been confused. Thanks for your great work.

Matt
